### ISSUE TITLE
Lost all folders and streams

### ISSUE THREAD

**Issue by SpoonOfDoom** [kgbergman/music-player#2]
Hey,
so we had a few weeks of hiatus in our campaign, so I haven't touched Owlbear in 3 weeks or so. Now I come back, and I notice that all the folders and streams I had added in Djinni were gone. Is this a bug, or do these things get removed after a while of inactivity or something?

Edit: I was just adding new things, then had an issue where it wouldn't play a certain youtube link, and after refreshing the page, everything I just added is gone again, so something is definitely up. Same happens when I go to the owlbear homepage and then enter the room again. Could it be something on my end? Doesn't look like there was an update for Djinni recently, so nothing should have changed.

**Comment by kgbergman** [comment]
You need to save your folders and reload them when you reopen a room using the save and open button in the header.

On Jun 12, 2024, at 11:57 AM, Christian Syska ***@***.***> wrote:

﻿

Hey,
so we had a few weeks of hiatus in our campaign, so I haven't touched Owlbear in 3 weeks or so. Now I come back, and I notice that all the folders and streams I had added in Djinni were gone. Is this a bug, or do these things get removed after a while of inactivity or something?

**Comment by SpoonOfDoom** [comment]
Okay, now I feel dumb. Was that always the case? I could swear I left and reentered the room many times when I last prepared a session and the changes always stayed.

**Comment by kgbergman** [comment]
Yep! 🙂 don’t feel dumb, several people have asked the same question! Maybe you just got lucky!

On Jun 12, 2024, at 12:24 PM, Christian Syska ***@***.***> wrote:

﻿

Okay, now I feel dumb. Was that always the case? I could swear I left and reentered the room many times when I last prepared a session and the changes always stayed.

**Comment by SpoonOfDoom** [comment]
Alright, then thanks and sorry for wasting your time! Would be a cool feature request though ;)

**Comment by kgbergman** [comment]
Unfortunately Owlbear Rodeo doesn’t allow devs to save anything within the app, which is why saving folders to a file is necessary. Otherwise I’d agree!

On Jun 12, 2024, at 1:11 PM, Christian Syska ***@***.***> wrote:

﻿

Alright, then thanks and sorry for wasting your time! Would be a cool feature request though ;)
